language: php
#php:
#  - '5.3'
#  - '5.4'
#  - '5.5'
#  - '5.6'
#  - '7.0'
#  - hhvm
#  - nightly
script: composer install  --no-interaction && ./vendor/bin/phpunit -c ./tests/configuration.xml --coverage-clover coverage tests
after_success:
  - bash <(curl -s https://codecov.io/bash)