language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit -c ./tests/configuration.xml --coverage-clover=coverage.xml tests

after_success:
    - bash <(curl -s https://codecov.io/bash)