<?php

namespace Ip;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-19 at 15:43:44.
 */
class UtilTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers Ip\Util::isIPv4
     */
    public function testIsIPv4()
    {
        $this->assertTrue(Util::isIPv4('0.0.0.0'));
        $this->assertTrue(Util::isIPv4('255.255.255.255'));

        $this->assertFalse(Util::isIPv4('-1.-1.-1.-1'));
        $this->assertFalse(Util::isIPv4('256.256.256.256'));
    }

    /**
     * @covers Ip\Util::isIPv6
     */
    public function testIsIPv6()
    {
        $this->assertTrue(Util::isIPv6('0:0:0:0:0:0:0:0'));
        $this->assertTrue(Util::isIPv6('FFFF:FFFF:FFFF:FFFF:FFFF:FFFF:FFFF:FFFF'));

        $this->assertFalse(Util::isIPv6('0:0:0:0:0:0:0:-1'));
//        $this->assertFalse(Util::isIPv6('FFFD:FFFD:FFFD:FFFD:FFFD:FFFD:FFFD:FFFD'));
        $this->assertFalse(Util::isIPv6('0.0.0.0'));
        $this->assertFalse(Util::isIPv6('255.255.255.255'));
    }

    /**
     * @covers Ip\Util::ipv4ToFloat
     */
    public function testIpv4ToFloat()
    {
        $this->assertEquals(0, Util::ipv4ToFloat('0.0.0.0'));
        $this->assertEquals(4294967295, Util::ipv4ToFloat('255.255.255.255'));
    }
}
